user_settings: 
  username: "bando00"
  jsessionid : "rYBIX2KtHAZXmjL3sPXTqimyOZUPOX57DKMyakWv"

base_api_settings:
  url: "http://localhost:8080/WebGoat/SqlInjection/"
  direct_query_addr: "attack2direct"
  direct_query: "SELECT * FROM employees;"

db_table_settings:
  table_name: "employees"
  column_names:
    - "userid"
    - "first_name"
    - "last_name"
    - "department"
    - "salary"
    - "auth_tan"
  column_datatypes:
    - "INT"
    - "TEXT"
    - "TEXT"
    - "TEXT"
    - "INT"
    - "TEXT"

api_endpoints_settings:
  - name: "Lesson 2"
    suffix: "attack2"
    parameters:
      - name: "query"
        type: "query"
        default_input: "Select department from employees where last_name = 'Franco'"
  
  - name : "Assignment 5b"
    suffix: "assignment5b"
    parameters:
      - name: "login_count"
        type: "string"
        default_input: "0" 
      - name : "userid"
        type: "string"
        default_input: "101"

  - name : "Assignment 5a"
    suffix: "attack8"
    parameters:
      - name: "name"
        type: "string"
        default_input: "Smith" 
      - name : "auth_tan"
        type: "string"
        default_input: "3SL99A"

  - name: "Lesson 3"
    suffix: "attack3"
    parameters:
      - name: "query"
        type: "query"
        default_input: "UPDATE employees SET department = 'Sales' WHERE first_name = 'Tobi' AND last_name = 'Barnett'"

  - name : "Lesson 4"
    suffix: "attack4"
    parameters:
      - name: "query"
        type: "query"
        default_input: "ALTER TABLE employees ADD phone varchar(20);"

  - name: "Assignment 5a"
    suffix: "assignment5a"
    parameters:
      - name: "account"
        type: "string"
        default_input: "Smith'"
      - name: "operator"
        type: "string"
        default_input: "OR"
      - name: "injection"
        type: "string"
        default_input: "'1'='1"

  - name: "Assignment 6a"
    suffix: "attack6a"
    parameters:
      - name: "userid_6a"
        type: "string"
        default_input: "Smith"

  - name: "Assignment 6b"
    suffix: "attack6b"
    parameters:
      - name: "userid_6b"
        type: "string"
        default_input: "passW0rD"