user_settings: 
  username: "bando00"
  jsessionid : "ZPSlG68WMwmcAAWZ1kGllV3GGeTtvIiJ0zKHZU-g"

base_api_settings:
  url: "http://localhost:8080/WebGoat/SqlInjection/"
  direct_query_addr: "attack2direct"
  direct_query: "SELECT * FROM employees;"

db_table_settings:
  table_name: "employees"
  column_names:
    - "userid"
    - "first_name"
    - "last_name"
    - "department"
    - "salary"
    - "auth_tan"
  column_datatypes:
    - "INT"
    - "TEXT"
    - "TEXT"
    - "TEXT"
    - "INT"
    - "TEXT"

api_endpoints_settings:
  - name: "Lesson 2"
    suffix: "attack2"
    parameters:
      - name: "query"
        type: "query"
        default_input: "Select department from employees where last_name = 'Franco'"
  
  - name : "Assignment 5b"
    suffix: "assignment5b"
    parameters:
      - name: "login_count"
        type: "string"
        default_input: "0" 
      - name : "userid"
        type: "string"
        default_input: "101"

  - name : "Assignment 5a"
    suffix: "attack8"
    parameters:
      - name: "name"
        type: "string"
        default_input: "Smith" 
      - name : "auth_tan"
        type: "string"
        default_input: "3SL99A"
