user_settings: 
  username: "bando00"
  jsessionid : "F_2BemzCMVh6z05wf4AWidDJ7XkGhkYjtv8eJpqc"

base_api_settings:
  url: "http://localhost:8080/WebGoat/SqlInjection/"
  direct_query_addr: "attack2direct"

api_endpopints_settings:
  - name: "Lesson 2"
    suffix: "attack2"
    parameters:
      - name: "query"
        type: "query"
        default: "Select department from employees where last_name = 'Franco'"
  
  - name : "Assignment 5b"
    suffix: "assignment5b"
    parameters:
      - name: "login_count"
        type: "string"
        default: "0" 
      - name : "userid"
        type: "string"
        default: "101"

  - name : "Assignment 5a"
    suffix: "attack8"
    parameters:
      - name: "name"
        type: "string"
        default: "Smith" 
      - name : "auth_tan"
        type: "string"
        default: "3SL99A"
