user_settings: 
  username: "bando00"
  jsessionid : "hQVSOWjKs-Bke2Jdo-ZliOd595xx5W3v6L5CV06N"

base_api_settings:
  url: "http://localhost:8080/WebGoat/"
  direct_query_addr: "SqlInjection/attack2direct"
  direct_query: "SELECT * FROM employees;"

db_table_settings:
  - table_name: "employees"
    column_names:
      - "userid"
      - "first_name"
      - "last_name"
      - "department"
      - "salary"
      - "auth_tan"
    column_datatypes:
      - "INT"
      - "TEXT"
      - "TEXT"
      - "TEXT"
      - "INT"
      - "TEXT"

  - table_name: "user_data"
    column_names:
      - "userid"
      - "first_name"
      - "last_name"
      - "cc_number"
      - "cc_type"
      - "cookie"
      - "login_count"
    column_datatypes:
      - "INT"
      - "TEXT"
      - "TEXT"
      - "TEXT"
      - "TEXT"
      - "TEXT"
      - "INT"

  - table_name: "user_system_data"
    column_names:
      - "userid"
      - "user_name"
      - "password"
      - "cookie"
    column_datatypes:
      - "INT"
      - "TEXT"
      - "TEXT"
      - "TEXT"

api_endpoints_settings:
  - name: "Lesson 2"
    suffix: "SqlInjection/attack2"
    table: "employees"
    parameters:
      - name: "query"
        type: "query"
        default_input: "Select department from employees where last_name = 'Franco'"
  
  - name : "Assignment 5b"
    suffix: "SqlInjection/assignment5b"
    table: "user_data"
    parameters:
      - name: "login_count"
        type: "string"
        default_input: "0" 
      - name : "userid"
        type: "string"
        default_input: "101"

  - name : "Assignment 5a"
    suffix: "SqlInjection/attack8"
    table: "employees"
    parameters:
      - name: "name"
        type: "string"
        default_input: "Smith" 
      - name : "auth_tan"
        type: "string"
        default_input: "3SL99A"

  - name: "Lesson 3"
    suffix: "SqlInjection/attack3"
    table: "employees"
    parameters:
      - name: "query"
        type: "query"
        default_input: "UPDATE employees SET department = 'Sales' WHERE first_name = 'Tobi' AND last_name = 'Barnett'"

  - name : "Lesson 4"
    suffix: "SqlInjection/attack4"
    table: "employees"
    parameters:
      - name: "query"
        type: "query"
        default_input: "ALTER TABLE employees ADD phone varchar(20);"

  - name: "Assignment 5a"
    suffix: "SqlInjection/assignment5a"
    table: "employees"
    parameters:
      - name: "account"
        type: "string"
        default_input: "Smith'"
      - name: "operator"
        type: "string"
        default_input: "OR"
      - name: "injection"
        type: "string"
        default_input: "'1'='1"

  - name: "Assignment 6a"
    suffix: "SqlInjectionAdvanced/attack6a"
    table: "user_data"
    parameters:
      - name: "userid_6a"
        type: "string"
        default_input: "Snow"

  - name: "Assignment 6b"
    suffix: "SqlInjectionAdvanced/attack6a"
    table: "user_system_data"
    parameters:
      - name: "password_6b"
        type: "string"
        default_input: "passW0rD"